# Generated by Django 4.2 on 2024-06-01 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_vehiculos', '0002_alter_vehiculo_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrocontabilidad',
            old_name='vehiculo_id',
            new_name='vehiculo',
        ),
    ]
